# Generated by Django 5.1.7 on 2025-03-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_tags',
            field=models.JSONField(default=list),
        ),
    ]
